/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marto_rtl_tcp_andro_tools_UsbPermissionHelper */

#ifndef _Included_marto_rtl_tcp_andro_tools_UsbPermissionHelper
#define _Included_marto_rtl_tcp_andro_tools_UsbPermissionHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     marto_rtl_tcp_andro_tools_UsbPermissionHelper
 * Method:    native_startUnixSocketServer
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_marto_rtl_1tcp_1andro_tools_UsbPermissionHelper_native_1startUnixSocketServer
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
