/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marto_rtl_tcp_andro_core_RtlTcp */

#ifndef _Included_marto_rtl_tcp_andro_core_RtlTcp
#define _Included_marto_rtl_tcp_andro_core_RtlTcp
#ifdef __cplusplus
extern "C" {
#endif
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_IO
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_IO -1L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_INVALID_PARAM
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_INVALID_PARAM -2L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_ACCESS
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_ACCESS -3L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_NO_DEVICE
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_NO_DEVICE -4L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_NOT_FOUND
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_NOT_FOUND -5L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_BUSY
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_BUSY -6L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_TIMEOUT
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_TIMEOUT -7L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_OVERFLOW
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_OVERFLOW -8L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_PIPE
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_PIPE -9L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_INTERRUPTED
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_INTERRUPTED -10L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_NO_MEM
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_NO_MEM -11L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_NOT_SUPPORTED
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_NOT_SUPPORTED -12L
#undef marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_OTHER
#define marto_rtl_tcp_andro_core_RtlTcp_LIBUSB_ERROR_OTHER -99L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_OK
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_OK 0L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_WRONG_ARGS
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_WRONG_ARGS 1L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_INVALID_FD
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_INVALID_FD 2L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_NO_DEVICES
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_NO_DEVICES 3L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_FAILED_TO_OPEN_DEVICE
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_FAILED_TO_OPEN_DEVICE 4L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_CANNOT_RESTART
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_CANNOT_RESTART 5L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_CANNOT_CLOSE
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_CANNOT_CLOSE 6L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_UNKNOWN
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_UNKNOWN 7L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_SIGNAL_CAUGHT
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_SIGNAL_CAUGHT 8L
#undef marto_rtl_tcp_andro_core_RtlTcp_EXIT_NOT_ENOUGH_POWER
#define marto_rtl_tcp_andro_core_RtlTcp_EXIT_NOT_ENOUGH_POWER 9L
/*
 * Class:     marto_rtl_tcp_andro_core_RtlTcp
 * Method:    open
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_marto_rtl_1tcp_1andro_core_RtlTcp_open
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     marto_rtl_tcp_andro_core_RtlTcp
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_marto_rtl_1tcp_1andro_core_RtlTcp_close
  (JNIEnv *, jclass);

/*
 * Class:     marto_rtl_tcp_andro_core_RtlTcp
 * Method:    isNativeRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_marto_rtl_1tcp_1andro_core_RtlTcp_isNativeRunning
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class marto_rtl_tcp_andro_core_RtlTcp_OnProcessTalkCallback */

#ifndef _Included_marto_rtl_tcp_andro_core_RtlTcp_OnProcessTalkCallback
#define _Included_marto_rtl_tcp_andro_core_RtlTcp_OnProcessTalkCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
