/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marto_rtl_tcp_andro_core_RtlTcp */

#ifndef _Included_marto_rtl_tcp_andro_core_RtlTcp
#define _Included_marto_rtl_tcp_andro_core_RtlTcp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     marto_rtl_tcp_andro_core_RtlTcp
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_marto_rtl_1tcp_1andro_core_RtlTcp_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     marto_rtl_tcp_andro_core_RtlTcp
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_marto_rtl_1tcp_1andro_core_RtlTcp_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class marto_rtl_tcp_andro_core_RtlTcp_OnProcessSaidWord */

#ifndef _Included_marto_rtl_tcp_andro_core_RtlTcp_OnProcessSaidWord
#define _Included_marto_rtl_tcp_andro_core_RtlTcp_OnProcessSaidWord
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class marto_rtl_tcp_andro_core_RtlTcp_OnProcessTalkCallback */

#ifndef _Included_marto_rtl_tcp_andro_core_RtlTcp_OnProcessTalkCallback
#define _Included_marto_rtl_tcp_andro_core_RtlTcp_OnProcessTalkCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
